[package]
name = "dwn-core"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true

[dependencies]
base64 = "0.22.1"
ipld-core = { version = "0.4.1", features = ["serde"] }
mime = "0.3.17"
serde.workspace = true
serde_ipld_dagcbor = "0.6.1"
serde_json = "1.0.128"
serde_with = "3.11.0"
thiserror.workspace = true
