[package]
name = "dwn"
description = "Rust implementation of a Decentralized Web Node."
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true

[features]
default = ["surrealdb"]
s3 = ["dep:rust-s3"]
surrealdb = ["dep:surrealdb", "dep:tokio"]

[dependencies]
aes-gcm = "0.10.3"
anyhow = "1.0.80"
base64 = "0.22.0"
did-method-key = "0.2.2"
didkit = { version = "0.6.0", default-features = false, features = ["ed25519"] }
iana-media-types = "0.1.2"
jsonschema = { version = "0.17.1", default-features = false, features = ["draft201909", "draft202012"] }
libipld = { version = "0.16.0", features = ["serde-codec"] }
libipld-cbor = "0.16.0"
libipld-core = { version = "0.16.0", features = ["serde", "serde-codec", "multibase"] }
reqwest = { version = "0.12.2", features = ["json"] }
rustls = { version = "0.23.4", default-features = false, features = ["ring", "logging", "std", "tls12"]}
semver = { version = "1.0.22", features = ["serde"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_ipld_dagcbor = "0.6.0"
serde_json.workspace = true
thiserror = "1.0.57"
time = { version = "0.3.31", features = ["serde-well-known"] }
tracing.workspace = true

rust-s3 = { version = "0.33.0", optional = true }
surrealdb = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }

[dev-dependencies]
surrealdb = { workspace = true, features = ["kv-mem"] }
tracing-subscriber.workspace = true
tracing-test = "0.2.4"
