[package]
name = "dwn"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true

[features]
default = ["native_db"]
native_db = ["dep:dwn-native-db"]

[dependencies]
base64 = "0.22.1"
dwn-core = { path = "../dwn-core" }
dwn-native-db = { path = "../dwn-native-db", optional = true }
jose-jwk = "0.1.2"
jsonschema = { version = "0.24.0", default-features = false, features = [
  "resolve-http",
  "draft201909",
  "draft202012",
] }
reqwest = "0.12.8"
ring = "0.17.8"
serde_json = "1.0.128"
thiserror.workspace = true
tracing.workspace = true
xdid.workspace = true

[dev-dependencies]
hyper = { version = "1.5.0", features = ["http1", "server"] }
hyper-util = "0.1.9"
port_check = "0.2.1"
tokio = { version = "1.40.0", features = ["macros", "rt", "rt-multi-thread"] }
tracing-test = { version = "0.2.5", features = ["no-env-filter"] }
