[package]
name = "dwn"
description = "Rust implementation of a Decentralized Web Node."
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true

[features]
default = ["surrealdb"]
mysql = ["dep:sqlx", "dep:tokio"]
s3 = ["dep:rust-s3"]
surrealdb = ["dep:surrealdb", "dep:tokio"]

[dependencies]
anyhow = "1.0.80"
async-recursion = "1.0.5"
base64 = "0.22.0"
did-method-key = "0.2.2"
didkit = { version = "0.6.0", default-features = false, features = ["ed25519"] }
iana-media-types = "0.1.2"
libipld = { version = "0.16.0", features = ["serde-codec"] }
libipld-cbor = "0.16.0"
libipld-core = { version = "0.16.0", features = ["serde", "serde-codec", "multibase"] }
openssl = "0.10.64"
serde = { version = "1.0.197", features = ["derive"] }
serde_ipld_dagcbor = "0.5.0"
serde_json = "1.0.114"
serde_with = "3.4.0"
thiserror = "1.0.57"
time = { version = "0.3.31", features = ["serde-well-known"] }
tracing.workspace = true

rust-s3 = { version = "0.33.0", optional = true }
sqlx = { version = "0.7.3", features = ["mysql", "time", "runtime-tokio", "tls-rustls"], optional = true }
tokio = { workspace = true, optional = true }

[target.'cfg(target_family = "wasm")'.dependencies]
surrealdb = { version = "1.2.2", default-features = false, features = ["kv-mem", "kv-indxdb"], optional = true }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
surrealdb = { version = "1.2.0", default-features = false, features = ["kv-mem", "kv-speedb"], optional = true }

[dev-dependencies]
tracing-subscriber = "0.3.18"
tracing-test = "0.2.4"
