[package]
name = "dwn"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true

[features]
native_db = ["dep:dwn-native-db"]

[dependencies]
dwn-core = { path = "../dwn-core" }
dwn-native-db = { path = "../dwn-native-db", optional = true }
thiserror.workspace = true
tracing.workspace = true
