[package]
name = "dwn-server"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true

[dependencies]
axum = "0.7.7"
axum-macros = "0.4.2"
dwn = { path = "../dwn" }
tracing.workspace = true
xdid.workspace = true
