[package]
name = "dwn-server"
description = "Decentralized Web Node HTTP server."
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true

[features]
default = ["surrealdb"]
surrealdb = ["dwn/surrealdb"]
mysql = ["dwn/mysql"]
s3 = ["dwn/s3"]

[dependencies]
axum = "0.7.2"
dwn.workspace = true
tokio.workspace = true
tracing.workspace = true
