[package]
name = "dwn-server"
description = "Decentralized Web Node HTTP server."
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true

[features]
default = ["surrealdb"]
surrealdb = ["dwn/surrealdb"]
s3 = ["dwn/s3"]

[dependencies]
axum = "0.7.5"
dwn.workspace = true
surrealdb = { version = "1.3.1", default-features = false, features = ["kv-speedb"] }
tokio.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
