[package]
name = "dwn-server"
description = "Decentralized Web Node HTTP server."
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true

[features]
default = ["surrealdb"]
surrealdb = ["dwn/surrealdb"]
s3 = ["dwn/s3"]

[dependencies]
axum = "0.7.2"
dwn.workspace = true
tracing.workspace = true

[dev-dependencies]
didkit.workspace = true
port_scanner = "0.1.5"
serde_json.workspace = true
surrealdb = { workspace = true, features = ["kv-mem"] }
tokio.workspace = true
tracing-test.workspace = true
