[package]
description = "Decentralized Web Node HTTP server."
edition.workspace = true
keywords.workspace = true
license.workspace = true
name = "dwn-server"
repository.workspace = true
version.workspace = true

[dependencies]
axum = "0.7.7"
axum-macros = "0.4.2"
dwn = { version = "0.1.0", path = "../dwn" }
tracing.workspace = true
xdid.workspace = true

[dev-dependencies]
port_check.workspace = true
tokio = { version = "1.40.0", features = ["macros", "rt", "rt-multi-thread"] }
tracing-test.workspace = true
