[package]
name = "dwn"
description = "Rust implementation of the Decentralized Web Node specification."
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
cid = "0.11.0"
libipld-core = "0.16.0"
libipld-pb = "0.16.0"
multihash-codetable = { version = "0.1.1", features = ["digest", "sha2"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_ipld_dagcbor = "0.4.2"
serde_json = "1.0.108"
