name: "CI"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: Swatinem/rust-cache@v2
      - run: nix develop -c cargo sqlx prepare --check --workspace -- --all-targets --all-features
      - run: nix develop -c cargo sqlx prepare --check --workspace -- --all-targets --all-features --tests
      - run: nix develop -c cargo clippy --fix --no-deps
      - run: nix develop -c cargo fmt --all
      - run: nix develop -c prettier -w .
      - uses: EndBug/add-and-commit@v9
        with:
          message: "chore: lint"
          default_author: github_actions
      - run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

  check:
    needs:
      - lint
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - uses: AdityaGarg8/remove-unwanted-software@v2
        with:
          remove-android: "true"
          remove-codeql: "true"
          remove-docker-images: "true"
          remove-dotnet: "true"
          remove-haskell: "true"
      - uses: actions/checkout@v4
        with:
          submodules: "true"
          ref: ${{ needs.lint.outputs.sha }}
      - uses: DeterminateSystems/flake-checker-action@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: Swatinem/rust-cache@v2
      - run: nix develop -c cargo doc --workspace --all-features --no-deps
      - run: nix develop -c cargo test --workspace --all-features
