name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: AdityaGarg8/remove-unwanted-software@v4
        with:
          remove-android: true
          remove-cached-tools: true
          # remove-codeql: true
          # remove-docker-images: true
          # remove-dotnet: true
          # remove-haskell: true
          # remove-large-packages: true
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: DeterminateSystems/flake-checker-action@v11
      - uses: DeterminateSystems/determinate-nix-action@v3
        with:
          extra-conf: extra-experimental-features = pipe-operators
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix flake check
      - run: nix develop -c cargo ws exec --no-bail -- cargo rdme --force
      - uses: EndBug/add-and-commit@v9
        with:
          message: "chore: generate README"
          default_author: github_actions
